### ISSUE TITLE
 practica-de-hilos-EdwinOrtizCruz

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/practica-de-hilos-EdwinOrtiz1412#2]
[Practica6_Edwin Ortiz Cruz_ 4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-EdwinOrtiz1412/files/8448278/Practica6_Edwin.Ortiz.Cruz_.4US.pdf)

**Comment by Sandra631** [comment]
20% bien hecho

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
